### ISSUE TITLE
TargetSdkVersion小于19时程序会异常报错

### ISSUE THREAD

**Issue by winston1991** [HalfStackDeveloper/SwipeCardRecyclerView#2]
com.wangxiandeng.swipecardrecyclerview E/AndroidRuntime: FATAL EXCEPTION: main java.lang.NoSuchMethodError: android.view.ViewPropertyAnimator.setUpdateListener                                                                                        at com.wangxiandeng.swipecardrecyclerview.SwipeCardRecyclerView.touchUp(SwipeCardRecyclerView.java:200)
                                                                                     at com.wangxiandeng.swipecardrecyclerview.SwipeCardRecyclerView.onTouchEvent(SwipeCardRecyclerView.java:109)
                                                                                          at android.view.View.dispatchTouchEvent(View.java:7385)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2206)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1941)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1955)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1955)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1955)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1955)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1955)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1955)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1966)
                                                                                          at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1418)
                                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2424)
                                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1914)
                                                                                          at android.view.View.dispatchPointerEvent(View.java:7565)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4167)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4061)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3582)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3632)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3601)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3609)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3582)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3632)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3601)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3609)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3582)
                                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5714)
                                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5683)
                                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5654)
                                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5788)
                                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
                                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                          at android.os.MessageQueue.next(MessageQueue.java:132)
                                                                                          at android.os.Looper.loop(Looper.java:124)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5136)
                                                                                          at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by HalfStackDeveloper** [comment]
应该是API 19下的属性动画没有setUpdateListener()方法
